#!/bin/bash

# silent prompt
read -p 'GIT profile: ' profile

# switch
case $profile in
  gotecq)
    git config --global user.email "phuc.tran@gotecq.com"
    git config --global user.name "gotecq-phuctran" 
    git config --global user.signingKey "id_rsa"
    ;;
  phuclynk)
    git config --global user.email "contact.huuphuc75@gmail.com"
    git config --global user.name "phuclynk" 
    git config --global user.signingKey "id_rsaaa"
    ;;
  # default case: raise error
  *)
    >&2 echo "ERR: Unknown profile: $profile"
    exit 1
esac